clear;clc

mach_num = 0;               % ambient mach number 
gamma_cold = 1.401;         % specific heat ratio for cold components [ambient, diffuser, compressor]
gamma_hot = 1.33;           % specific heat ratio for hot components [burner, turbine, nozzle]
specHeat_cold = 1004;       % specific heat for cold components [J/kgK]
specHeat_hot = 1156;        % specific heat for hot components [J/kgK]
heatrxn_fuel = 42800000;    % heat of combustion of jetA [J/kg]


num_HP_compressors = 2;
num_LP_compressors = 3;
num_HP_turbines = 2;
num_LP_turbines = 3;

Turbojet = struct( ...
    "Info", [],...
    "Compressor", struct( ...
        "HP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_HP_compressors, 1), ...
        "LP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_LP_compressors, 1) ...
        ), ...
    "Combustor", [], ...
    "Turbine", struct( ...
        "HP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_HP_turbines, 1), ...
        "LP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_LP_turbines, 1) ...
        ) ...
    );





% asdf = Turbojet.Turbine.LP(3).P1;