clear;clc

num_HP_compressors = 2;
num_LP_compressors = 3;
num_HP_turbines = 2;
num_LP_turbines = 3;

Turbojet = struct( ...
    "Info", [],...
    "Compressor", struct( ...
        "HP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_HP_compressors, 1), ...
        "LP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_LP_compressors, 1) ...
        ), ...
    "Combustor", [], ...
    "Turbine", struct( ...
        "HP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_HP_turbines, 1), ...
        "LP", repmat(struct( ...
            "P1", [], ...
            "P01", []), ...
            num_LP_turbines, 1) ...
        ) ...
    );

asdf = Turbojet.Turbine.LP(3).P1